### ISSUE TITLE
Can I calculate the accuracy of the SE-SSD model in ROS wrapper ?

### ISSUE THREAD

**Issue by hsihsii** [StephLin/SE-SSD-ROS#12]
Hello ~ Thanks for your work！I tried to  use on Ubuntu 20.04 , ROS noetic , CUDA11.1 It's very well~
How can I display the Average Precision (AP) when running the ros_main.py ?

**Comment by StephLin** [comment]
Hi @hsihsii,

This wrapper does not input ground truth detections. It cannot output average precision.
Instead, you could compute AP outside the wrapper:

1. Suppose you have a dataset with pairs of LiDAR scans and ground truth detections
2. Feed LiDAR scans to the wrapper, receive the detection from the wrapper, and store the detection results following the data structure defined by 3rd-party benchmarking tools (e.g, traveller59's [kitti-object-eval-python](https://github.com/traveller59/kitti-object-eval-python)).
3. Use that 3rd-party benchmarking tool to compute AP.

Or you may consider [the original SE-SSD's repository](https://github.com/Vegeta2020/SE-SSD). It provides some tools to evaluate the detection results as well.

**Comment by mantruong204** [comment]
> Hello ~ Thanks for your work！I tried to use on Ubuntu 20.04 , ROS noetic , CUDA11.1 It's very well~ How can I display the Average Precision (AP) when running the ros_main.py ?

Hello, how could you install the source with cuda 11.1, i had tried with both cuda <10.2 or >10.2 and it lead to error. Does the source required exactly cuda 10.2 for installation? Or, I can modify somewhere to adapt with other cuda versions?

**Comment by hsihsii** [comment]
> > Hello ~ Thanks for your work！I tried to use on Ubuntu 20.04 , ROS noetic , CUDA11.1 It's very well~ How can I display the Average Precision (AP) when running the ros_main.py ?
> 
> Hello, how could you install the source with cuda 11.1, i had tried with both cuda <10.2 or >10.2 and it lead to error. Does the source required exactly cuda 10.2 for installation? Or, I can modify somewhere to adapt with other cuda versions?

Hello @mantruong204 ,
I installed the original SE-SSD library with CUDA 11.1 .
Could you please specify the error message you encountered?

**Comment by hsihsii** [comment]
> Hi @hsihsii,
> 
> This wrapper does not input ground truth detections. It cannot output average precision. Instead, you could compute AP outside the wrapper:
> 
> 1. Suppose you have a dataset with pairs of LiDAR scans and ground truth detections
> 2. Feed LiDAR scans to the wrapper, receive the detection from the wrapper, and store the detection results following the data structure defined by 3rd-party benchmarking tools (e.g, traveller59's [kitti-object-eval-python](https://github.com/traveller59/kitti-object-eval-python)).
> 3. Use that 3rd-party benchmarking tool to compute AP.
> 
> Or you may consider [the original SE-SSD's repository](https://github.com/Vegeta2020/SE-SSD). It provides some tools to evaluate the detection results as well.

Hello StephLin ,
Thank you very much!!
