### ISSUE TITLE
Support to VLP-16 or other low-line LiDAR?

### ISSUE THREAD

**Issue by qpc001** [StephLin/SE-SSD-ROS#7]

**Comment by StephLin** [comment]
Hi @qpc001,

In my opinion, the protocol supports for other LiDAR scanners, but the performance might not be guaranteed. As this project is a ROS wrapper of [SE-SSD](https://github.com/Vegeta2020/SE-SSD), I suggest you to ask SE-SSD's maintainers for performance issues.
