### ISSUE TITLE
Questions about the relationship between test results and lio-segmot

### ISSUE THREAD

**Issue by dkjsednfkjsn** [StephLin/SE-SSD-ROS#9]
Hello author, if you use python3 ros_main.py to run 3D target detection and pass the message to lio-segmot, how can you know that the result is passed correctly? Because I tested and found that the lio-segmot algorithm does not seem to receive the detection results. Looking forward to your reply, thank you.

**Comment by StephLin** [comment]
Hi @dkjsednfkjsn,

Please describe steps to setup SE-SSD-ROS.

Note that LIO-SEGMOT views SE-SSD-ROS as a ROS service. Perhaps you could check if the following command works for you:

```bash
python3 ros_main.py --mode lio_segmot
```

**Comment by dkjsednfkjsn** [comment]
> Hi @dkjsednfkjsn,
> 
> Please describe your steps to setup SE-SSD-ROS.
> 
> Note that LIO-SEGMOT views SE-SSD-ROS as a ROS service. Perhaps you could check if the following command works for you:
> 
> ```shell
> python3 ros_main.py --mode lio_segmot
> ```

Thank you for your reply, I'm sorry for asking such a basic question, after reading your code I understand the problem, thank you for your work!
